# Generated by Django 3.0.8 on 2020-07-29 18:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eshop', '0002_auto_20200729_1354'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='imageurl',
            field=models.CharField(max_length=100000),
        ),
    ]
